remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Paul Friedman for Congress"
description: "Paul Friedman :: IL-09 CD"
